#!/usr/bin/zsh

zmodload zsh/mathfunc

battery_path='/sys/class/power_supply/BAT0'
backlight_path='/sys/class/backlight/intel_backlight'

energy_full_design=45.0
energy_full=$[float($(<$battery_path/energy_full))/10**6]
energy_now=$[float($(<$battery_path/energy_now))/10**6]
power_now=$[float($(<$battery_path/power_now))/10**6]

case $(<$battery_path/status) in
  'Charging')
    hours=$[(${energy_full}-${energy_now})/${power_now}]
    ;;
  'Discharging')
    hours=$[${energy_now}/${power_now}]
    power_now=$[-1.0*${power_now}]
    ;;
  *)
    c='?'
    hours=0
    ;;
esac

energy_full_p=$[100*$energy_full/$energy_full_design]
energy_now_p=$[100*$energy_now/$energy_full]
brightness_p=$[100.*$(<$backlight_path/brightness)/$(<$backlight_path/max_brightness)]

printf "design:      %5.1f Wh\n" $energy_full_design
printf "last full:   %5.1f Wh [%3.1f%%]\n" $energy_full $energy_full_p
printf "remaining:   %5.1f Wh [%3.1f%%]\n" $energy_now $energy_now_p
printf "rate:       %+6.1f W\n" $power_now
printf "time:        %5.1f h\n" $hours
printf "brightness:  %5.1f%%\n" $brightness_p
