#!/usr/bin/bash

# verify two files are identical

_hash () {
  sha512sum "$1" | tee /dev/stderr | head -c 128
}

a=$(_hash "$1")
b=$(_hash "$2")

if [[ "$a" == "$b" ]]; then
  echo PASSED
  ret=0
else
  echo FAILED
  ret=1
fi

exit $ret
