#!/usr/bin/bash

# wrapper for managing truecrypt volumes

usage () {
  echo "usage: $0 {m,mount,u,umount} truecrypt_file"
  exit 1
}

cmd=$1
tcfile=$2

[[ -z "$cmd" || -z "$tcfile" ]] && usage

tcname=$(basename $tcfile)
mountdir=/tmp/$tcname


case $cmd in
  m|mount) 
    [[ -d $mountdir ]] || mkdir $mountdir
    chmod 600 $mountdir
    sudo cryptsetup -v open --type tcrypt $tcfile $tcname
    sudo mount -v -o uid=$(id -u),gid=$(id -g),fmask=0177,dmask=0077 /dev/mapper/$tcname $mountdir
    ;;

  u|umount)
    sudo umount -v $mountdir
    sudo cryptsetup -v close $tcname
    rmdir $mountdir
    ;;

  *)
    usage
    ;;
esac
