#!/usr/bin/bash

# KDE4 desktop files do not behave correctly outside of a full DE

destdir=$HOME/.local/share/applications/kde4
[[ -d $destdir ]] || mkdir -p $destdir

for i in /usr/share/applications/kde4/*.desktop; do
  if egrep -q '^Exec=.* (%i|-caption %c)' $i; then
    bn=$(basename $i)
    echo "fixing $bn"
    sed \
      -e 's: %i::' $i \
      -e 's: -caption %c::' $i \
      > $destdir/$bn
  fi
done
