#!/usr/bin/env python3

""" Read an array from stdin and write to a numpy file. """

import sys

import numpy as np


def main():
    if len(sys.argv) != 2:
        print('usage: {} output_file'.format(sys.argv[0]))
        exit(1)

    filename = sys.argv[1]

    arr = np.array([l.split() for l in sys.stdin.buffer],
                   dtype=float).squeeze()
    np.save(filename, arr)


if __name__ == "__main__":
    main()
