#!/usr/bin/bash

# pacman cleanup

echo 'removing orphans'
[[ $(pacman -Qdt) ]] && sudo pacman -Rs $(pacman -Qdtq)
echo

source /etc/makepkg.conf
pc="/usr/bin/paccache \
  --remove --verbose \
  --cachedir $(pacman-conf CacheDir) \
  --cachedir $PKGDEST \
"

echo 'pruning cache - uninstalled pkgs'
$pc --uninstalled --keep 0
echo

echo 'pruning cache - old versions'
$pc --keep 2

exit 0
