#!/usr/bin/zsh

# tidy up files from my Canon camera

for i in IMG*.JPG; do
  chmod -v 644 $i
  mv -v $i img_`date -r $i +%Y.%m.%d_%H:%M:%S`.jpg
done

for i in *.MOV; do
  chmod -v 644 $i
  mv -v $i mvi_`date -r $i +%Y.%m.%d_%H:%M:%S`.mov
done
