#!/usr/bin/bash

# toggle unblock-us dns

sed_resolvconf () {
  sudo sed -i "$1" /etc/resolv.conf
}

pattern='nameserver 208.122.23.2[23]'

case $1 in
  'on')  sed_resolvconf "s/^#\($pattern\)/\1/" ;;
  'off') sed_resolvconf "s/^\($pattern\)/#\1/" ;;
  *) echo "usage: $0 {on|off}" && exit 1 ;;
esac
