#!/usr/bin/bash

# update profile-sync-daemon

set -e

if pgrep chromium &> /dev/null; then
  echo 'chromium running'
  exit 1
fi

echo 'stopping psd'
sudo systemctl stop psd

packer -S --noconfirm profile-sync-daemon

[[ -f /etc/psd.conf.pacnew ]] && sudo vimdiff /etc/psd.conf{,.pacnew}

echo 'reloading daemons'
sudo systemctl daemon-reload

echo 'starting psd'
sudo systemctl start psd

echo 'done'
