#!/usr/bin/bash

# automate updating profile-sync-daemon

if pgrep chromium &> /dev/null; then
  echo 'chromium running'
  exit 1
fi

echo 'stopping psd'
systemctl --user stop psd

pacaur --sync --noconfirm profile-sync-daemon

vimdiff ~/.config/psd/psd.conf /usr/share/doc/psd/psd.conf

echo 'reloading daemons'
systemctl --user daemon-reload

echo 'starting psd'
systemctl --user start psd

echo 'done'
