#!/usr/bin/bash

# wifi management shortcuts

case $1 in
  st|status) 
    sudo wpa_cli status
    echo 
    iw dev wlan0 link 
    echo -en '\n        ' 
    iw dev wlan0 get power_save 
    echo 
    ip addr show wlan0
    ;;

  ip)
    sudo dhcpcd -n wlan0
    ;;

  sc|scan)
    sudo iw dev wlan0 scan | less
    ;;

  pwr|power|power_save)
    sudo iw dev wlan0 set power_save $2
    ;;

  rs|restart|stop|start)
    [[ $1 == 'rs' ]] && cmd='restart' || cmd=$1
    sudo systemctl $cmd netctl-auto@wlan0.service
    ;;

  *) 
    cat <<EOF
usage:  $0 command

  st|status             : assorted status information
  ip                    : renew DHCP
  sc|scan               : scan for networks
  pwr|power|power_save  : toggle power saving
  rs|restart|stop|start : manage netctl auto wireless
EOF
    ;;
esac
